// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoko.Plugin.Anilist.Storage;

#nullable disable

namespace Shoko.Plugin.Anilist.Storage.Migrations
{
    [DbContext(typeof(AnilistDbContext))]
    [Migration("20260926131252_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Shoko.Plugin.Anilist.Storage.AnilistStoredAnime", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLicensed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MalID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeanScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Season")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("INTEGER");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Recommendations", "Shoko.Plugin.Anilist.Storage.AnilistStoredAnime.Recommendations#AnilistStoredRecommendation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("ID");

                            b1.Property<int?>("Score");

                            b1
                                .ToJson("Recommendations")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("ID");

                    b.ToTable("Anime", (string)null);
                });

            modelBuilder.Entity("Shoko.Plugin.Anilist.Storage.AnilistStoredEpisode", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnimeID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("AnimeID");

                    b.ToTable("Episodes", (string)null);
                });

            modelBuilder.Entity("Shoko.Plugin.Anilist.Storage.AnilistStoredPortrait", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Portraits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
